### ISSUE TITLE
21 pin B4 compatible STL file

### ISSUE THREAD

**Issue by PaulKennett** [dalathegreat/Nissan-Leaf-Battery-to-OBD2#1]
You may be interested in my 21 pin version of the B24 plug and socket:

https://www.myminifactory.com/object/3d-print-nissan-leaf-b24-compatible-connector-93715

Cheers, Paul

**Comment by cgalpin** [comment]
I had not noticed that you had made a 21 pin connector @PaulKennett before making my own! I probably should make a locking ring too, but it's not really needed for just the Nissan-Leaf-Battery-to-OBD2.

@dalathegreat mine is just the connector similar to your 2013+ one, and can make a merge request with updated documentation if interested.

**Comment by dalathegreat** [comment]
@cgalpin Absolutely feel free! :)

**Comment by PaulKennett** [comment]
@cgalpin Yeah - If you ever do print one with the locking ring - add a little grease to the inside of the ring to get a smooth slide action.

**Comment by cgalpin** [comment]
Ok @dalathegreat, pull request #2 created. 

@PaulKennett, I did not take the time to make a locking ring. I had not looked at yours before making mine (and if I had, I likely would not have bothered to make my own), nor am I sure if yours would be compatible - but if you think it would bet, let me know.
